### ISSUE TITLE
Update to babel 5.0

### ISSUE THREAD

**Issue by natew** [SimonDegraeve/react-class-helper#2]
Using this will cause a weird bug if you're running babel 5.0, I think if you upgrade your build step to use the latest it will fix it.

**Comment by ThomWright** [comment]
Is the bug that `Object.assign` doesn't work? Because I'm getting that... :(

**Comment by SimonDegraeve** [comment]
This project is no longer maintained, please use [react-mixin](https://github.com/brigand/react-mixin) instead.
